name: Deploy Dist
on: [push,workflow_dispatch]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              run: git clone https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Get code
              run: |
                echo "clonig repo...."
                echo "${{toJson(github)}}"
                git clone https://github.com/${{github.repository}}.git